### PR TITLE
add support for more chromium-based web browsers; edit some bash scripts; vietnamese translation

### PR DESCRIPTION
**Pull request by shadichy**

### CODE REVIEW

**Comment by eltonfabricio10** [comment]
Opera has no support for Webapps.
To test: `opera --app="https://google.com"`

Opera ignores the flag _--app_

**Comment by shadichy** [comment]
> Opera has no support for Webapps. To test: `opera --app="https://google.com"`
> 
> Opera ignores the flag _--app_

sr, just forgot that, will fix that soon

**Comment by shadichy** [comment]
@eltonfabricio10 done. have a look please.

**Comment by eltonfabricio10** [comment]
Please wait... 
I will add support for FlatPak browsers and several fixes

**Comment by shadichy** [comment]
> Please wait... I will add support for FlatPak browsers and several fixes

will waterfox, slimjet and some electron-based browsers/pwa clients be added?

**Comment by eltonfabricio10** [comment]
waterfox: waterfox-g ?

slimjet: I will add

electron-based browsers/pwa clients: Any example?

**Comment by shadichy** [comment]
> waterfox: waterfox-g ?
> 
> slimjet: I will add
> 
> electron-based browsers/pwa clients: Any example?

4get about waterfox, it sucks

electron-based browsers/pwa clients: nodejs-nativefier, electron-pwa-wrapper, or electron itself

**Comment by eltonfabricio10** [comment]
We don't need the Opera icon

**Comment by eltonfabricio10** [comment]
How to activate the right click menu on Electron?

**Comment by shadichy** [comment]
> We don't need the Opera icon

will delete it

**Comment by shadichy** [comment]
> How to activate the right click menu on Electron?

you can't, electron isn't a web browser

**Comment by eltonfabricio10** [comment]
Update your system and test this:
`python3 /usr/lib/bbv/client.py https://google.com -s 900x600`

I think better than Electron and we can use it as a fallback

**Comment by shadichy** [comment]
> I think better than Electron and we can use it as a fallback

or mark it as an option

**Comment by eltonfabricio10** [comment]
Waiting for more PRs :)

**Comment by shadichy** [comment]
> Waiting for more PRs :)

aww thanks

**Comment by eltonfabricio10** [comment]
Crashed :(

**Comment by shadichy** [comment]
> Crashed :(

oh no

**Comment by shadichy** [comment]
@eltonfabricio10  detail please

**Comment by eltonfabricio10** [comment]
the installed webapps are opening normally, however when clicking on Add or Remove Webapps in menu the forum is opening

**Comment by eltonfabricio10** [comment]
Bug in biglinux-webapps command

**Comment by shadichy** [comment]
> the installed webapps are opening normally, however when clicking on Add or Remove Webapps in menu the forum is opening

oh my bad :) sorry about that, will fix it asap

image
image

**Pull request merged**
