### PR TITLE
re-added support for various browsers; added bbv-client as fallback option; added wrapper for firefoxpwa as fallback option; re-stylesheet; better browser detector

### PR DESCRIPTION
**Pull request by shadichy**

### CODE REVIEW

**Comment by shadichy** [comment]
@eltonfabricio10 what do you think?

**Comment by eltonfabricio10** [comment]
I will test

**Comment by shadichy** [comment]
how is it going?

**Comment by eltonfabricio10** [comment]
It has to be native firefox

**Comment by shadichy** [comment]
> It has to be native firefox

native firefox does not support pwa by default (blame Mozilla). if you still want to keep it, I'll add it back asap

**Comment by shadichy** [comment]
also, note that this (upstream build) doesn't work
image

**Comment by eltonfabricio10** [comment]
update your PR, please...

**Comment by eltonfabricio10** [comment]
Not appears others browsers

Screenshot_20230203_185026

Screenshot_20230203_185233


Bash error
Screenshot_20230203_185314

**Comment by shadichy** [comment]
> Not appears others browsers

Which browsers do you have?
(edit: please list as _repo_name/browser_package_name_)

**Comment by eltonfabricio10** [comment]
Those who were already appearing on the program.

**Comment by shadichy** [comment]
> Those who were already appearing on the program.

 i mean the installed ones, not those listed by the program

**Comment by eltonfabricio10** [comment]
> i mean the installed ones, not those listed by the program

Screenshot_20230124_061708

**Comment by eltonfabricio10** [comment]
After [6cc1407](https://github.com/biglinux/biglinux-webapps/pull/13/commits/6cc140789077b6f3c706d11d0b12bd671d8173c1)

Screenshot_20230204_084021

browsers repeat

**Comment by shadichy** [comment]
> After [6cc1407](https://github.com/biglinux/biglinux-webapps/pull/13/commits/6cc140789077b6f3c706d11d0b12bd671d8173c1)
> 
> Screenshot_20230204_084021
> 
> browsers repeat

inspect element please?

**Comment by shadichy** [comment]
here still no prob
image

**Comment by eltonfabricio10** [comment]
> inspect element please?

Screenshot_20230204_095628

Screenshot_20230204_095919

**Comment by shadichy** [comment]
> > inspect element please?
> 
> Screenshot_20230204_095628
> 
> Screenshot_20230204_095919

so it was because of this
image

**Comment by eltonfabricio10** [comment]
js: Uncaught Error: Syntax error, unrecognized expression: button#/usr/bin/electron

**Comment by eltonfabricio10** [comment]
js: Uncaught Error: Syntax error, unrecognized expression: button#/usr/bin/electron

**Comment by shadichy** [comment]
image
seems good

**Comment by eltonfabricio10** [comment]
Why 2 Firefox native?

**Comment by shadichy** [comment]
> Why 2 Firefox native?

the left one is the original firefox, while the right one is firefoxpwa
image

**Comment by eltonfabricio10** [comment]
```
/usr/bin/biglinux-webapp: line 59: /electron: No such file or directory
/usr/bin/biglinux-webapp: line 59: /bbv-client: No such file or directory
/usr/bin/biglinux-webapp: line 59: /brave: No such file or directory

/change_browser.sh /electron /bbv-client
/change_browser.sh /bbv-client /brave
```

**Comment by shadichy** [comment]
> ```
> /usr/bin/biglinux-webapp: line 59: /electron: No such file or directory
> /usr/bin/biglinux-webapp: line 59: /bbv-client: No such file or directory
> /usr/bin/biglinux-webapp: line 59: /brave: No such file or directory
> 
> /change_browser.sh /electron /bbv-client
> /change_browser.sh /bbv-client /brave
> ```

my bad

**Comment by shadichy** [comment]
is there any problem left?

**Comment by eltonfabricio10** [comment]
I'm still testing it, please wait

**Comment by eltonfabricio10** [comment]
Problems with the last commit:

- The multi-icon modal appears without the icons
- When selecting electron or another browser to open the default webapps... The browser is opened without the url
- It was much slower to open the webapps manager

Final considerations:
Many unnecessary changes that compromise the functioning of the program. If you still want to do some PR, do it without changing the basic structure.

I'm going to close this PR... sorry!

**Comment by shadichy** [comment]
detail please?

**Pull request closed without merging**
