### PR TITLE
Fixed `biglinux-webapps` opens forum page

### PR DESCRIPTION
**Pull request by shadichy**

### CODE REVIEW

**Comment by shadichy** [comment]
@eltonfabricio10 problem fixed

**Comment by eltonfabricio10** [comment]
OK, let's go :)

**Comment by eltonfabricio10** [comment]
Firefox and Epiphany was missing to add Webapps.
But in standard webapps can' t have.

**Comment by shadichy** [comment]
> Firefox and Epiphany was missing to add Webapps. But in standard webapps can' t have.

my bad again :) so sorry

**Comment by eltonfabricio10** [comment]
Any changes to the project must add features or bring improvements and never modify the original purpose.

**Comment by shadichy** [comment]
i need to figure out the way to parse `--app` argument to epiphany understandable format

**Pull request merged**
